/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import ClasesNormales.CasaApuestas;
import ClasesNormales.JugadorRegistrado;
import ClasesNormales.Premio;
import java.util.ArrayList;
import javax.swing.JTextArea;

/**
 *
 * @author Danil
 */
public class VentanaEstadisticas extends javax.swing.JFrame {
    ArrayList<JugadorRegistrado> jugadores= new ArrayList<>();
    /**
     * Creates new form VentanaEstadisticas
     */
    public VentanaEstadisticas() {
        initComponents();
        jugadores.addAll(CasaApuestas.jugadores.values());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaEstadisticas = new javax.swing.JTextArea();
        jLabelPOKER = new javax.swing.JLabel();
        jTextFieldTipoDePremio = new javax.swing.JTextField();
        jLabelTipoDePremio = new javax.swing.JLabel();
        jButtonCantidadPremio = new javax.swing.JButton();
        jButtonJugadoresPremiados = new javax.swing.JButton();
        jLabelNombreJugador = new javax.swing.JLabel();
        jTextFieldJugador = new javax.swing.JTextField();
        jButtonMesa = new javax.swing.JButton();
        jButtonIndividual = new javax.swing.JButton();
        jButtonTodos = new javax.swing.JButton();
        jButtonCantidadPremioMesa = new javax.swing.JButton();
        jButtonCantidadPremioIndividual = new javax.swing.JButton();
        jTextFieldCantidad = new javax.swing.JTextField();
        jLabelCantidad = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("POKERFLOW");

        jTextAreaEstadisticas.setEditable(false);
        jTextAreaEstadisticas.setColumns(20);
        jTextAreaEstadisticas.setRows(5);
        jScrollPane1.setViewportView(jTextAreaEstadisticas);

        jLabelPOKER.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelPOKER.setForeground(new java.awt.Color(0, 204, 204));
        jLabelPOKER.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPOKER.setText("POKERFLOW");

        jLabelTipoDePremio.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelTipoDePremio.setText("Tipo de Premio a Buscar:");

        jButtonCantidadPremio.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonCantidadPremio.setText("Cantidad de Veces que ha salido");
        jButtonCantidadPremio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCantidadPremioActionPerformed(evt);
            }
        });

        jButtonJugadoresPremiados.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonJugadoresPremiados.setText("Jugadores que lo han obtenido");
        jButtonJugadoresPremiados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJugadoresPremiadosActionPerformed(evt);
            }
        });

        jLabelNombreJugador.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelNombreJugador.setText("Jugador a Buscar (NIF):");

        jButtonMesa.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonMesa.setText("Premios en Mesa (Jugador)");
        jButtonMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMesaActionPerformed(evt);
            }
        });

        jButtonIndividual.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonIndividual.setText("Premios Individual (Jugador)");
        jButtonIndividual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIndividualActionPerformed(evt);
            }
        });

        jButtonTodos.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonTodos.setText("Todos los Premios (Jugador)");
        jButtonTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTodosActionPerformed(evt);
            }
        });

        jButtonCantidadPremioMesa.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonCantidadPremioMesa.setText("Cantidad de Veces de un Premio en Mesa (Jugador)");
        jButtonCantidadPremioMesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCantidadPremioMesaActionPerformed(evt);
            }
        });

        jButtonCantidadPremioIndividual.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonCantidadPremioIndividual.setText("Cantidad de Veces de un Premio Individual (Jugador)");
        jButtonCantidadPremioIndividual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCantidadPremioIndividualActionPerformed(evt);
            }
        });

        jTextFieldCantidad.setEditable(false);

        jLabelCantidad.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabelCantidad.setText("Veces que ha salido:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldTipoDePremio)
                            .addComponent(jButtonCantidadPremio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelTipoDePremio)
                            .addComponent(jButtonJugadoresPremiados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldJugador)
                            .addComponent(jLabelNombreJugador)
                            .addComponent(jButtonMesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonIndividual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonTodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonCantidadPremioMesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonCantidadPremioIndividual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelCantidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelPOKER, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(298, 298, 298))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPOKER, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabelTipoDePremio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTipoDePremio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCantidadPremio, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonJugadoresPremiados, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelNombreJugador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonIndividual, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonTodos, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCantidadPremioMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCantidadPremioIndividual, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCantidad)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCantidadPremioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCantidadPremioActionPerformed
        // TODO add your handling code here:
        int contador=0;
        for (int i = 0; i < jugadores.size(); i++) {
            for(int j=0; j < jugadores.get(i).getPremios().size(); j++){               
                if (jugadores.get(i).getPremios().get(j).getTipoPremio().equals(jTextFieldTipoDePremio.getText().toUpperCase())) {
                    contador++;     
                }           
            }
        }
        jTextFieldCantidad.setText(String.valueOf(contador));
    }//GEN-LAST:event_jButtonCantidadPremioActionPerformed

    private void jButtonJugadoresPremiadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJugadoresPremiadosActionPerformed
        // TODO add your handling code here:
        jTextAreaEstadisticas.setText("");
        ArrayList<JugadorRegistrado> jugadoresPremiados= new ArrayList<>();
        for (int i = 0; i < jugadores.size(); i++) {
            for (int j = 0; j < jugadores.get(i).getPremios().size(); j++) {
                if (jugadores.get(i).getPremios().get(j).getTipoPremio().equals(jTextFieldTipoDePremio.getText().toUpperCase()) && !jugadoresPremiados.contains(jugadores.get(i))) {
                    jugadoresPremiados.add(jugadores.get(i));
                }               
            }           
        }
        for (JugadorRegistrado jr: jugadoresPremiados) {
            this.setjTextAreaEstadisticas(this.getjTextAreaEstadisticas().getText()+ "Jugador: "+ jr.getNombre()+ " " + jr.getApellidos() + " NIF: "+jr.getNIF()+'\n');
        }
    }//GEN-LAST:event_jButtonJugadoresPremiadosActionPerformed

    private void jButtonMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMesaActionPerformed
        // TODO add your handling code here:
        jTextAreaEstadisticas.setText("");
        ArrayList<Premio> premios= new ArrayList<>();
        JugadorRegistrado jugador= CasaApuestas.jugadores.get(jTextFieldJugador.getText());
        for (int i = 0; i < jugador.getPremios().size(); i++) {
            if (jugador.getPremios().get(i).getTipoJuego().equals("Mesa")) {
                premios.add(jugador.getPremios().get(i));
            }            
        }
        for (int i = 0; i < premios.size(); i++) {
            this.setjTextAreaEstadisticas(this.getjTextAreaEstadisticas().getText()+ premios.get(i).toString() +'\n');            
        }
    }//GEN-LAST:event_jButtonMesaActionPerformed

    private void jButtonIndividualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIndividualActionPerformed
        // TODO add your handling code here:
        jTextAreaEstadisticas.setText("");
        ArrayList<Premio> premios= new ArrayList<>();
        JugadorRegistrado jugador= CasaApuestas.jugadores.get(jTextFieldJugador.getText());
        for (int i = 0; i < jugador.getPremios().size(); i++) {
            if (jugador.getPremios().get(i).getTipoJuego().equals("Individual")) {
                premios.add(jugador.getPremios().get(i));
            }            
        }
        for (int i = 0; i < premios.size(); i++) {
            this.setjTextAreaEstadisticas(this.getjTextAreaEstadisticas().getText()+ premios.get(i).toString() +'\n');            
        }
    }//GEN-LAST:event_jButtonIndividualActionPerformed

    private void jButtonTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTodosActionPerformed
        // TODO add your handling code here:
        jTextAreaEstadisticas.setText("");
        JugadorRegistrado jugador= CasaApuestas.jugadores.get(jTextFieldJugador.getText());
        for (int i = 0; i < jugador.getPremios().size(); i++) {
            this.setjTextAreaEstadisticas(this.getjTextAreaEstadisticas().getText()+ jugador.getPremios().get(i).toString() +'\n');            
        }
    }//GEN-LAST:event_jButtonTodosActionPerformed

    private void jButtonCantidadPremioMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCantidadPremioMesaActionPerformed
        // TODO add your handling code here:
        jTextAreaEstadisticas.setText("");
        int contador=0;
        ArrayList<Premio> premios= new ArrayList<>();
        JugadorRegistrado jugador= CasaApuestas.jugadores.get(jTextFieldJugador.getText());
        for (int i = 0; i < jugador.getPremios().size(); i++) {
            if (jugador.getPremios().get(i).getTipoJuego().equals("Mesa")) {
                premios.add(jugador.getPremios().get(i));
            }            
        }
        for (int i = 0; i < premios.size(); i++) {
            if (premios.get(i).getTipoPremio().equals(jTextFieldTipoDePremio.getText().toUpperCase())) {
                contador++;
            }            
        }
        jTextFieldCantidad.setText(String.valueOf(contador));
    }//GEN-LAST:event_jButtonCantidadPremioMesaActionPerformed

    private void jButtonCantidadPremioIndividualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCantidadPremioIndividualActionPerformed
        // TODO add your handling code here:
        jTextAreaEstadisticas.setText("");
        int contador=0;
        ArrayList<Premio> premios= new ArrayList<>();
        JugadorRegistrado jugador= CasaApuestas.jugadores.get(jTextFieldJugador.getText());
        for (int i = 0; i < jugador.getPremios().size(); i++) {
            if (jugador.getPremios().get(i).getTipoJuego().equals("Individual")) {
                premios.add(jugador.getPremios().get(i));
            }            
        }
        for (int i = 0; i < premios.size(); i++) {
            if (premios.get(i).getTipoPremio().equals(jTextFieldTipoDePremio.getText().toUpperCase())) {
                contador++;
            }            
        }
        jTextFieldCantidad.setText(String.valueOf(contador));
    }//GEN-LAST:event_jButtonCantidadPremioIndividualActionPerformed

    /**
     *
     * @return
     */
    public JTextArea getjTextAreaEstadisticas() {
        return jTextAreaEstadisticas;
    }
    
    /**
     *
     * @param ListaJugadores
     */
    public void setjTextAreaEstadisticas(String ListaJugadores) {
        this.jTextAreaEstadisticas.setText(ListaJugadores);
    }

    /**
     *
     * @param args
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEstadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEstadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEstadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEstadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEstadisticas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCantidadPremio;
    private javax.swing.JButton jButtonCantidadPremioIndividual;
    private javax.swing.JButton jButtonCantidadPremioMesa;
    private javax.swing.JButton jButtonIndividual;
    private javax.swing.JButton jButtonJugadoresPremiados;
    private javax.swing.JButton jButtonMesa;
    private javax.swing.JButton jButtonTodos;
    private javax.swing.JLabel jLabelCantidad;
    private javax.swing.JLabel jLabelNombreJugador;
    private javax.swing.JLabel jLabelPOKER;
    private javax.swing.JLabel jLabelTipoDePremio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaEstadisticas;
    private javax.swing.JTextField jTextFieldCantidad;
    private javax.swing.JTextField jTextFieldJugador;
    private javax.swing.JTextField jTextFieldTipoDePremio;
    // End of variables declaration//GEN-END:variables
}
