/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import ClasesNormales.Apuesta;
import ClasesNormales.Baraja;
import ClasesNormales.Carta;
import ClasesNormales.JugadorException;
import ClasesNormales.JugadorOcasional;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Danil
 */
public class VentanaIndividualOcasional extends javax.swing.JFrame {
    ArrayList<Carta> manoO= new ArrayList<>();
    ArrayList<Carta> barajaO= new ArrayList<>();  
    JugadorOcasional jugadorO= VentanaDatosOcasional.jo;
    /**
     * Creates new form VentanaIndividualOcasional
     */
    public VentanaIndividualOcasional() {
        initComponents();
        jTextFieldResultado.setText("0");
        jTextFieldAumentarSaldo.setText("0");
        jTextFieldApuesta.setText("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPOKER = new javax.swing.JLabel();
        jLabelAumentarSaldo = new javax.swing.JLabel();
        jTextFieldAumentarSaldo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButtonAumentarSaldo = new javax.swing.JButton();
        jLabelApuesta = new javax.swing.JLabel();
        jTextFieldApuesta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabelRetirarBeneficios = new javax.swing.JLabel();
        jTextFieldBeneficio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldSaldoRestante = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButtonJugar = new javax.swing.JButton();
        jLabelCarta1 = new javax.swing.JLabel();
        jLabelCarta2 = new javax.swing.JLabel();
        jLabelCarta3 = new javax.swing.JLabel();
        jLabelCarta4 = new javax.swing.JLabel();
        jLabelCarta5 = new javax.swing.JLabel();
        jLabelSaldoResultante = new javax.swing.JLabel();
        jTextFieldResultado = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jButtonRetirarBeneficios = new javax.swing.JButton();
        jButtonImprimirFactura = new javax.swing.JButton();
        jTextFieldPremio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("POKERFLOW");

        jLabelPOKER.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelPOKER.setForeground(new java.awt.Color(0, 204, 204));
        jLabelPOKER.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPOKER.setText("POKERFLOW");

        jLabelAumentarSaldo.setText("¿Aumentar Saldo?");

        jTextFieldAumentarSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAumentarSaldoActionPerformed(evt);
            }
        });

        jLabel2.setText("€");

        jButtonAumentarSaldo.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButtonAumentarSaldo.setText("Aumentar Saldo");
        jButtonAumentarSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAumentarSaldoActionPerformed(evt);
            }
        });

        jLabelApuesta.setText("Apuesta:");

        jLabel4.setText("€");

        jLabelRetirarBeneficios.setText("¿Retirar Beneficios?");

        jTextFieldBeneficio.setEditable(false);

        jLabel6.setText("Beneficio:");

        jLabel7.setText("Saldo Restante:");

        jTextFieldSaldoRestante.setEditable(false);

        jLabel8.setText("€");

        jLabel9.setText("€");

        jButtonJugar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonJugar.setText("JUGAR");
        jButtonJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJugarActionPerformed(evt);
            }
        });

        jLabelSaldoResultante.setText("Saldo Resultante:");

        jTextFieldResultado.setEditable(false);

        jLabel16.setText("€");

        jButtonRetirarBeneficios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonRetirarBeneficios.setText("Retirar Beneficios");
        jButtonRetirarBeneficios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetirarBeneficiosActionPerformed(evt);
            }
        });

        jButtonImprimirFactura.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonImprimirFactura.setText("Imprimir Factura");
        jButtonImprimirFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimirFacturaActionPerformed(evt);
            }
        });

        jTextFieldPremio.setEditable(false);
        jTextFieldPremio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextFieldPremio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldPremio.setText("--");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAumentarSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jTextFieldAumentarSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addGap(168, 168, 168)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelApuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldApuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldBeneficio))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldSaldoRestante, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabelCarta1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelCarta2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCarta3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCarta4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCarta5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addComponent(jLabelSaldoResultante, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldPremio, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addComponent(jLabelPOKER, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(332, 332, 332)
                            .addComponent(jButtonJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(57, 57, 57)
                            .addComponent(jButtonAumentarSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonRetirarBeneficios, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonImprimirFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelRetirarBeneficios, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPOKER, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonImprimirFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAumentarSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelApuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelRetirarBeneficios))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldApuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldAumentarSaldo))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldBeneficio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jTextFieldSaldoRestante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAumentarSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jButtonRetirarBeneficios, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(70, 70, 70)
                .addComponent(jButtonJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelCarta5, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(jLabelCarta4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCarta3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCarta2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCarta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelSaldoResultante, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPremio, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldAumentarSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAumentarSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAumentarSaldoActionPerformed

    private void jButtonJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJugarActionPerformed
        // TODO add your handling code here:
        try{
            if(Integer.parseInt(jTextFieldApuesta.getText())>jugadorO.getSaldoAcumulado()){
                throw new JugadorException(JugadorException.SALDO_INSUFICIENTE);
            }
            manoO.clear();
            barajaO=Baraja.creaBaraja();
            manoO=Baraja.creaMano(barajaO);
            barajaO.clear();
            jugadorO.actualizaSaldo(manoO,Integer.parseInt(jTextFieldApuesta.getText()));
            jTextFieldResultado.setText(String.valueOf(jugadorO.getSaldoAcumulado()));
            ImageIcon imagen1 = new ImageIcon("CartasEspañolas/" + manoO.get(0).toString());
            ImageIcon imgRedimensionada1 = new ImageIcon(imagen1.getImage().getScaledInstance(jLabelCarta1.getWidth(), jLabelCarta1.getHeight(), 1));
            jLabelCarta1.setIcon(imgRedimensionada1);
            ImageIcon imagen2 = new ImageIcon("CartasEspañolas/" + manoO.get(1).toString());
            ImageIcon imgRedimensionada2 = new ImageIcon(imagen2.getImage().getScaledInstance(jLabelCarta2.getWidth(), jLabelCarta2.getHeight(), 1));
            jLabelCarta2.setIcon(imgRedimensionada2);
            ImageIcon imagen3 = new ImageIcon("CartasEspañolas/" + manoO.get(2).toString());
            ImageIcon imgRedimensionada3 = new ImageIcon(imagen3.getImage().getScaledInstance(jLabelCarta3.getWidth(), jLabelCarta3.getHeight(), 1));
            jLabelCarta3.setIcon(imgRedimensionada3);
            ImageIcon imagen4 = new ImageIcon("CartasEspañolas/" + manoO.get(3).toString());
            ImageIcon imgRedimensionada4 = new ImageIcon(imagen4.getImage().getScaledInstance(jLabelCarta4.getWidth(), jLabelCarta4.getHeight(), 1));
            jLabelCarta4.setIcon(imgRedimensionada4);
            ImageIcon imagen5 = new ImageIcon("CartasEspañolas/" + manoO.get(4).toString());
            ImageIcon imgRedimensionada5 = new ImageIcon(imagen5.getImage().getScaledInstance(jLabelCarta5.getWidth(), jLabelCarta5.getHeight(), 1));
            jLabelCarta5.setIcon(imgRedimensionada5);
            jTextFieldPremio.setText(Apuesta.verPremioTexto(Apuesta.verPremio(manoO)));
        
        } catch(JugadorException je){
            JOptionPane.showMessageDialog(this, je.toString(), "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonJugarActionPerformed

    private void jButtonAumentarSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAumentarSaldoActionPerformed
        // TODO add your handling code here:
        jugadorO.aumentarSaldo(Double.parseDouble(jTextFieldAumentarSaldo.getText()));
        jTextFieldResultado.setText(String.valueOf(jugadorO.getSaldoAcumulado()));
    }//GEN-LAST:event_jButtonAumentarSaldoActionPerformed

    private void jButtonRetirarBeneficiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetirarBeneficiosActionPerformed
        // TODO add your handling code here:
        jTextFieldBeneficio.setText(String.valueOf(jugadorO.retirarBeneficios()));
        jTextFieldSaldoRestante.setText(String.valueOf(jugadorO.getSaldoAcumulado()));
    }//GEN-LAST:event_jButtonRetirarBeneficiosActionPerformed

    private void jButtonImprimirFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimirFacturaActionPerformed
        // TODO add your handling code here:
        PrintWriter salida = null;
        try {
            // TODO add your handling code here:    public static void generaFicha(Persona per) throws IOException {
            salida = new PrintWriter(new BufferedWriter(new FileWriter(jugadorO.getNIF() + ".txt")));
            salida.println("-------------------------------- Ficha "+ jugadorO.getNombre() +" --------------------------------");
            salida.println("\n");
            salida.println("DNI: " + jugadorO.getNIF());
            salida.println("\n");
            salida.println("Nombre: " + jugadorO.getNombre());
            salida.println("\n");
            salida.println("Fecha de nacimiento: " + jugadorO.getFechaNacimiento());
            salida.println("\n");
            salida.println("Beneficio: " + jTextFieldBeneficio.getText() + "€");
            salida.println("\n");
            salida.println("\n");
            salida.println("-------------------------------------------------------------------------------");
        } catch (IOException ex) {
            Logger.getLogger(VentanaIndividualOcasional.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            salida.close();
        }
    }//GEN-LAST:event_jButtonImprimirFacturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaIndividualOcasional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaIndividualOcasional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaIndividualOcasional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaIndividualOcasional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaIndividualOcasional().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAumentarSaldo;
    private javax.swing.JButton jButtonImprimirFactura;
    private javax.swing.JButton jButtonJugar;
    private javax.swing.JButton jButtonRetirarBeneficios;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelApuesta;
    private javax.swing.JLabel jLabelAumentarSaldo;
    private javax.swing.JLabel jLabelCarta1;
    private javax.swing.JLabel jLabelCarta2;
    private javax.swing.JLabel jLabelCarta3;
    private javax.swing.JLabel jLabelCarta4;
    private javax.swing.JLabel jLabelCarta5;
    private javax.swing.JLabel jLabelPOKER;
    private javax.swing.JLabel jLabelRetirarBeneficios;
    private javax.swing.JLabel jLabelSaldoResultante;
    private javax.swing.JTextField jTextFieldApuesta;
    private javax.swing.JTextField jTextFieldAumentarSaldo;
    private javax.swing.JTextField jTextFieldBeneficio;
    private javax.swing.JTextField jTextFieldPremio;
    private javax.swing.JTextField jTextFieldResultado;
    private javax.swing.JTextField jTextFieldSaldoRestante;
    // End of variables declaration//GEN-END:variables
}
